### ISSUE TITLE
Turn on filter?

### ISSUE THREAD

**Issue by yisibl** [ssssota/svg2png-wasm#37]
resvg now disables SVG filter by default.

**Comment by ssssota** [comment]
@yisibl 

I could not find any information about this in the resvg documentation.

Can you please provide more details?

**Comment by yisibl** [comment]
All you need to do is add a filter to Cargo.toml.

```toml
resvg = { version = "0.19.0", default-features = false, features = ["filter"] }
usvg = { version = "0.19.0", default-features = false, features = [ "filter"] }
```
